FROM golang:1.17.8-alpine

COPY ./ /src/
WORKDIR /src/cmd

RUN ls -la

RUN CGO_ENABLED=0 GOOS=linux go build -o WebCrawler 

FROM --platform=linux/x86_64 chromedp/headless-shell:latest
RUN apt update && apt install dumb-init
# ENTRYPOINT ["dumb-init", "--"]
COPY --from=0 /src/cmd/WebCrawler /
CMD ./WebCrawler